---
abstract: 'extract the unique elements of a list'
author:
  - "James FitzGibbon\n<james+perl@nadt.net>"
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Uniq
provides:
  List::Uniq:
    file: lib/List/Uniq.pm
    version: v0.21.0
resources:
  license: http://dev.perl.org/licenses/
version: v0.21.0
